WARNINGS := -Wall 
DEBUG := -g

CFLAGS += $(WARNINGS) $(DEBUG) 

all:
	make mem_capacity mem_capacity2 unit_s
clean:
	rm -f mem_capacity unit_s mem_capacity2 mem_bw
capacity:
	make mem_capacity mem_capacity2
unit:
	make unit_s
bw:
	make mem_bw
